#!/usr/bin/env bash

_wsl-keychain-load () {
  local cur prev words cword

  _init_completion || return

  case "$prev" in
    load|save)
      _filedir
      return
      ;;
  esac

  case "$cur" in
    -*)
      COMPREPLY=($(compgen -W '$( _parse_help "$1" )' -- "$cur"))
      return
      ;;
  esac

  if [ "$cword" -eq 1 ]; then
    COMPREPLY=($(compgen -W 'init load save' -- "$cur"))
  fi
} && complete -F _wsl-keychain-load wsl-keychain-load
