#!/usr/bin/env bash

_bookmark () {
  local cur prev words cword

  _init_completion || return

  case "$prev" in
    file)
      _filedir
      return
      ;;
    list)
      COMPREPLY=($(compgen -W "$(bookmark list --name 2>/dev/null)" -- "$cur"))
      return
      ;;
    open)
      COMPREPLY=($(compgen -W "$(bookmark list --name 2>/dev/null)" -- "$cur"))
      return
      ;;
    url)
      COMPREPLY=($(compgen -W "$(bookmark urls --target 2>/dev/null)" -- "$cur"))
      return
      ;;
  esac

  case "$cur" in
    -*)
      COMPREPLY=($(compgen -W '$( _parse_help "$1" )' -- "$cur"))
      return
      ;;
  esac

  if [ "$cword" -eq 1 ]; then
    COMPREPLY=($(compgen -W 'file files list open url urls' -- "$cur"))
  fi
} && complete -F _bookmark bookmark
