name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Install bats
        run: sudo npm install -g bats

      - name: Lint
        run: make lint

      - name: Unit test
        run: make unit

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Install help2man
        run: sudo apt-get install help2man

      - name: Install Gemfile bundle
        run: bundle install

      - name: Install Node modules
        run: npm install

      - name: Build
        run: make build

      - name: Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dotfiles.zip
          path: dist/dotfiles.zip
