name: CI

on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotfiles.zip
          path: dist/dotfiles.zip
