name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Package
        run: make package

      - name: Changelog
        id: changelog
        run: |
          contents="$(sed -e '1,/##/d' -e '/##/,$d' CHANGELOG.md)"
          contents="${contents//'%'/'%25'}"
          contents="${contents//$'\n'/'%0A'}"
          contents="${contents//$'\r'/'%0D'}"
          echo "::set-output name=contents::$contents"

      - name: Create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.contents }}
          draft: false
          prerelease: false

      - name: Upload package
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/dotfiles.zip
          asset_name: dotfiles.zip
          asset_content_type: application/zip
