name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Install bats
        run: sudo npm install -g bats

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Install help2man
        run: sudo apt-get install help2man

      - name: Install Gemfile bundle
        run: bundle install

      - name: Install Node modules
        run: npm install

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Package
        run: make package

      - name: Changelog
        id: changelog
        run: |
          contents="$(sed -e '1,/##/d' -e '/##/,$d' CHANGELOG.md)"
          contents="${contents//'%'/'%25'}"
          contents="${contents//$'\n'/'%0A'}"
          contents="${contents//$'\r'/'%0D'}"
          echo "::set-output name=contents::$contents"

      - name: Create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.contents }}
          draft: false
          prerelease: false

      - name: Upload package
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/dotfiles.zip
          asset_name: dotfiles.zip
          asset_content_type: application/zip
